name: rise-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - matplotlib
    - MIDIUtil
    - ipywidgets
    - numpy
    - seaborn
    - music21
    - ipython
    - librosa
